// lib/whatsapp.ts
import FormData from 'form-data';
import fs from 'fs';
import { createReadStream } from 'fs';

const PHONE_ID = process.env.WHATSAPP_PHONE_ID;
const TOKEN = process.env.WHATSAPP_TOKEN;

/**
 * Uploads a generated PDF to WhatsApp servers.
 * Returns the Media ID required to send the document.
 */
export async function uploadMedia(filePath: string): Promise<string | null> {
  if (!PHONE_ID || !TOKEN) {
    console.log("⚠️ WhatsApp Credentials missing in .env.local");
    return null;
  }

  const form = new FormData();
  form.append('messaging_product', 'whatsapp');
  // Use createReadStream for memory efficiency with files
  form.append('file', createReadStream(filePath));
  form.append('type', 'application/pdf');

  try {
    const response = await fetch(`https://graph.facebook.com/v17.0/${PHONE_ID}/media`, {
      method: 'POST',
      body: form as any, // Cast to any because of FormData/Fetch type conflicts in Node
      headers: {
        'Authorization': `Bearer ${TOKEN}`,
        ...form.getHeaders()
      }
    });

    const data = await response.json() as { id?: string; error?: any };
    
    if (data.id) {
      console.log("☁️ PDF Uploaded to WhatsApp. Media ID:", data.id);
      return data.id;
    } else {
      console.error("❌ Upload Failed:", data.error || data);
      return null;
    }
  } catch (error) {
    console.error("❌ Network Error (Upload):", error);
    return null;
  }
}

/**
 * Sends the PDF document to the customer's WhatsApp number.
 */
export async function sendInvoicePDF(toMobile: string, mediaId: string): Promise<boolean> {
  if (!mediaId || !PHONE_ID || !TOKEN) return false;

  const payload = {
    messaging_product: "whatsapp",
    to: toMobile,
    type: "document",
    document: {
      id: mediaId,
      filename: "invoice.pdf",
      caption: "Here is your invoice, Sir! \nGenerated by *VoiceInvoice AI* 🤖"
    }
  };

  try {
    const response = await fetch(`https://graph.facebook.com/v17.0/${PHONE_ID}/messages`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${TOKEN}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    });

    const data = await response.json() as { messages?: Array<{ id: string }>, error?: any };
    
    if (data.messages?.[0]?.id) {
      console.log("✅ Invoice SENT to customer!");
      return true;
    } else {
      console.error("❌ Send Failed:", data.error || data);
      return false;
    }
  } catch (error) {
    console.error("❌ Network Error (Send):", error);
    return false;
  }
}

/**
 * Fetches the temporary URL for an audio message and downloads it.
 * Returns the audio file as a Base64 string for Gemini processing.
 */
export async function downloadWhatsAppMedia(mediaId: string): Promise<string | null> {
  if (!mediaId || !TOKEN) return null;

  try {
    // A. Get the media URL from Meta
    const urlResponse = await fetch(`https://graph.facebook.com/v17.0/${mediaId}`, {
      headers: { 'Authorization': `Bearer ${TOKEN}` }
    });
    const urlData = await urlResponse.json() as { url?: string };
    const mediaUrl = urlData.url;

    if (!mediaUrl) {
      console.error("❌ Could not retrieve media URL from WhatsApp.");
      return null;
    }

    // B. Download the Binary Data using the provided URL
    const fileResponse = await fetch(mediaUrl, {
      headers: { 'Authorization': `Bearer ${TOKEN}` }
    });
    
    // C. Convert to Buffer then Base64
    const arrayBuffer = await fileResponse.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    
    console.log(`⬇️ Downloaded Real Audio: ${buffer.length} bytes`);
    return buffer.toString('base64');

  } catch (error) {
    console.error("❌ Error Downloading Media:", error);
    return null;
  }
}